### ISSUE TITLE
exec /influxdb-relay failed: No such file or directory

### ISSUE THREAD

**Issue by TimothyGaray** [bitnami/bitnami-docker-influxdb-relay#1]
**Description**

Trying to run latest version of the container.  It will not run stating
     exec /influxdb-relay failed: No such file or directory

**Steps to reproduce the issue:**

1. docker run --init -d --name influxdb-relay -v /mnt/data/influxdb.relay/relay.toml:/relay.toml --restart=unless-stopped -p 9096:9096 bitnami/influxdb-relay:latest /influxdb-relay --config /relay.toml

**Describe the results you received:**
From the docker logs:
[FATAL tini (6)] exec /influxdb-relay failed: No such file or directory
[FATAL tini (6)] exec /influxdb-relay failed: No such file or directory
[FATAL tini (6)] exec /influxdb-relay failed: No such file or directory
[FATAL tini (6)] exec /influxdb-relay failed: No such file or directory
[FATAL tini (6)] exec /influxdb-relay failed: No such file or directory

**Describe the results you expected:**

Container to run.

**Additional information you deem important (e.g. issue happens only occasionally):**

N/A

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:52 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 6
  Running: 5
  Paused: 0
  Stopped: 1
 Images: 6
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-53-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.663GiB
 Name: intelnuc5a
 ID: KCG2:5PLP:YIQG:QMJR:QQUC:DG7O:WA3W:KWNK:ICRO:FMIJ:VJID:6PRZ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: timothygaray
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.5
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
IntelNUC running Ubuntu server 20.04.

**Comment by carrodher** [comment]
Hi, thanks for reporting the issue. There is a mismatch between the binary name and the documentation.
At this moment the binary is named `influxdb_relay` (underscore) while the documentation says `influxdb-relay` (hyphen). As the binary in the upstream project is named `influxdb-relay`, we are going to release a new version of this container fixing the typo.

In the meantime, you can use the container as it is but using `... /influxdb_relay --config /relay.toml` (with the underscore) in your `docker run` command.

**Comment by TimothyGaray** [comment]
Thank you, that worked as a workaround.

**Comment by carrodher** [comment]
We just released a new image with the proper binary name, see https://github.com/bitnami/bitnami-docker-influxdb-relay/commit/bb8f748f5587c4a478211fe9d7ed1df8ae6ebd07

Now you should be able to follow the README instructions as well as the instructions from the upstream project since the binary is using the proper name, `influxdb-relay`. Feel free to reopen the issue if you face any other problem. Thanks
